### ISSUE TITLE
Missing dependency and rosbag2 not fully removed

### ISSUE THREAD

**Issue by AlexisTM** [ros2/rmw_iceoryx#3]
The build currently fails:

Logging from rosbag2 not fully removed.

https://github.com/ros2/rmw_iceoryx/blob/5ea38cb7a489379fba554136e741eda428bd012a/iceoryx_ros2_bridge/src/generic_subscription.cpp#L115-L116

Missing `std_msgs` dependency from `package.xml` for `iceoryx_ros2_bridge` which cannot be found in the CMakeLists.txt: 

https://github.com/ros2/rmw_iceoryx/blob/5ea38cb7a489379fba554136e741eda428bd012a/iceoryx_ros2_bridge/CMakeLists.txt#L31

**Comment by Karsten1987** [comment]
Thanks @AlexisTM for bringing this up. That's the price you pay when you don't immediately set up CI for it. If you have a chance to check out #4 that would be great.

**Comment by AlexisTM** [comment]
It fixes the build and we can use rmw_iceoryx_cpp out of the box using #4.
