### ISSUE TITLE
doesn't build with ros2 foxy

### ISSUE THREAD

**Issue by freyjax** [ros2/rmw_iceoryx#38]
fatal error: rosidl_generator_c/primitives_sequence.h: No such file or directory

error occurs during colcon build

**Comment by budrus** [comment]
Thanks @freyjax. I guess the last update was with some commits before the final foxy release. @Karsten1987 can you have a look?

**Comment by ralph-lange** [comment]
I was able to build ros2/rmw_iceoryx and eclipse-iceoryx/iceoryx in one workspace together using colcon build, when choosing the foxy branch of ros2/rmw_iceoryx and the v0.17.0 tag of eclipse-iceoryx/iceoryx.

**Comment by budrus** [comment]
Thanks for the feedback @ralph-lange. We broke the API with the 0.90.0 release,  a pre-release for iceoryx_1.0.0 which is planned for 03/2020 and will have a stable LTS API. When the 1.0.0 release is available it makes sense to update rmw_iceoryx. There will be lots of features that can make rmw_iceoryx much better

**Comment by mossmaurice** [comment]
@freyjax Closing this issue as rmw_iceoryx was updated with iceoryx v1.0.1 support in #42. Feel free to re-open if it persists!
