### ISSUE TITLE
`ros2 topic echo` not working

### ISSUE THREAD

**Issue by mossmaurice** [ros2/rmw_iceoryx#57]
## Required information

**Operating system:**
Ubuntu 20.04.02 LTS

**Compiler version:**
GCC 9.3.0

**Branch:**
galactic

**Observed result or behaviour:**
`ros2 topic echo` not working, no output just seems to be blocked

**Expected result or behaviour:**
Increasing counter is shown in cmd line

**Conditions where it occurred / Performed steps:**
`RMW_IMPLEMENTATION=rmw_iceoryx_cpp ros2 topic echo /chatter` does not print any output when running the talker/listener demo

**Comment by nistran** [comment]
Same Issue here. 
ROS2 Galactic with Ubuntu 20.04.
```ros2 topic list``` works as expected
```ros2 topic echo``` and ```ros2 topic hz``` does not work. 
Any news here?
Thanks.

**Comment by mossmaurice** [comment]
Thanks for the ping @nistran! Not solved yet. This is also the reason why there is no release yet for galactic. I'll have a closer look on what's the issue. 

IIRC @ZhenshengLee was looking into this a while ago. Maybe he gained some insight?

**Comment by ZhenshengLee** [comment]
were you able to check whether this works? https://answers.ros.org/question/384441/how-to-debug-rmw-segfaults-launched-by-ros2cli-like-ros2-topic-echo/?answer=384845#post-id-384845

_Originally posted by @christophebedard in https://github.com/ros2/rmw_iceoryx/issues/49#issuecomment-907422149_

I think this would help to debug python based ros2 application.

**Comment by mossmaurice** [comment]
@nistran @ZhenshengLee I opened PR #70 which fixes Python support and `ros2 topic echo` for me. Could you please have a look?

The Python debugging hint from @christophebedard worked like a charm :rocket:

**Comment by mossmaurice** [comment]
Fixed with #70
