### ISSUE TITLE
Python Nodes  issues with rmw_iceoryx

### ISSUE THREAD

**Issue by nistran** [ros2/rmw_iceoryx#69]
HI Everyone
I had some tests with rmw_iceoryx and python nodes. 
Somehow I'm not able to receive any message with a pyhon node. I think this correlates with the issue #57 . As far as I know ros topic is a python based application. 
Trying to publish a message via a python node leads me to another issue. When I call ``` ros2 topic echo <topic name>``` I get the error ```The message type 'std_msgs/msg/' is invalid```.
Does anyone has an advice using python nodes in rmw_iceoryx?
Thank you in advance.

**Comment by mossmaurice** [comment]
Hi @nistran
Thanks for creating the issue! I've not used Python together with `rmw_iceoryx` myself. I suppose your assumption that #57 is related is correct. However, I won't close this as a duplicate yet because this issue can be re-used to create some Python examples or tests in the CI.

**Comment by mossmaurice** [comment]
Fixed by #70, CI tests using Python will be covered in #46. Closing this issue. Feel free to re-open if the issue persist.
