### ISSUE TITLE
Compatibility with eclipse/iceoryx

### ISSUE THREAD

**Issue by jeising** [ros2/rmw_iceoryx#8]
### Issue

`ros2/rmw_iceoryx` and `eclipse/iceoryx` on their current masters seem to be incompatible. Therefore the getting started section in the readme.md is not working.

Maybe there should be a .repos file in this or a separate repo which is to be used to get a list of compatible rmw and iceoryx versions.

Also it would be good to have a badge, which shows the ci status for this package.

### Error Message

``` bash
2020-02-05 12:34:50.518 [ Info  ]: Application registered management segment 0x7f34414a8000 with size 113271904 to id 1
2020-02-05 12:34:50.519 [ Info  ]: Application registered payload segment 0x7f341daba000 with size 595259200 to id 2
2020-02-05 12:34:50.520 [ Error ]: Wrong response from message queue
python3: /opt/iceoryx/src/iceoryx/iceoryx_posh/source/runtime/posh_runtime.cpp:302: iox::runtime::RunnableData* iox::runtime::PoshRuntime::createRunnable(const iox::runtime::RunnableProperty&): Assertion `false' failed.
Aborted (core dumped)
```

### Personal setup

Using docker image `osrf/ros:eloquent-desktop` and installing `iceoryx` and `rmw_iceoryx` according to `readme.md`

### Expected behavior

As for the tags in these repos, which seem to compatible indicated by identical naming, I would expect the corresponding master branches to be compatible, too.

**Comment by michael-poehnl** [comment]
I guess we broke the fix we already made for this in one of the last merges in iceoryx. This was already fixed here but is back again
https://github.com/eclipse/iceoryx/pull/24

**Comment by michael-poehnl** [comment]
will be fixed with https://github.com/eclipse/iceoryx/pull/41

**Comment by michael-poehnl** [comment]
Was merged with https://github.com/eclipse/iceoryx/pull/41
